### ISSUE TITLE
Set up event bus

### ISSUE THREAD

**Issue by giorgiosironi** [libero/walking-skeleton#27]
From https://elifesciences.atlassian.net/browse/ELPP-3620

Basic setup in https://github.com/libero/walking-skeleton/pull/18 as part of ELPP-3622

https://github.com/libero/walking-skeleton/pull/25/files#diff-4e5e90c6228fd48698d074241c2ba760R112 incidentally adds persistence.

**Comment by giorgiosironi** [comment]
Has been done as part of other pull requests?

**Comment by thewilkybarkid** [comment]
Think it's been done.
