### ISSUE TITLE
Article store Airflow integration

### ISSUE THREAD

**Issue by seanwiseman** [libero/walking-skeleton#33]
Add functionality to communicate with an Airflow instance in the form of one or more DAG(s) which demonstrate a logical and extensible integration.

- [x] Add Airflow services to project level `docker-compose.yml`
- [x] Draft requirements for tasks and a target DAG
- [x] Create tasks and DAG
- [x] Create basic adapter for the article store to talk to Airflow
- [x] Implement initiating the DAG from the article store

**Comment by giorgiosironi** [comment]
With the current `master` I get these on `docker-compose up -V`:
```
article-store-airflow-webserver_1  | Fri May 25 15:37:41 UTC 2018 - waiting for Postgres... 18/20
article-store-airflow-flower_1     | Fri May 25 15:37:41 UTC 2018 - waiting for Redis... 19/20
article-store-airflow-scheduler_1  | Fri May 25 15:37:42 UTC 2018 - waiting for Postgres... 18/20
article-store-airflow-worker_1     | Fri May 25 15:37:42 UTC 2018 - waiting for Postgres... 18/20
article-store-airflow-webserver_1  | Fri May 25 15:37:46 UTC 2018 - waiting for Postgres... 19/20
article-store-airflow-flower_1     | Fri May 25 15:37:46 UTC 2018 - localhost:6379 still not reachable, giving up
walking-skeleton_article-store-airflow-flower_1 exited with code 1
article-store-airflow-scheduler_1  | Fri May 25 15:37:47 UTC 2018 - waiting for Postgres... 19/20
article-store-airflow-worker_1     | Fri May 25 15:37:48 UTC 2018 - waiting for Postgres... 19/20
article-store-airflow-webserver_1  | Fri May 25 15:37:51 UTC 2018 - localhost:5432 still not reachable, giving up
walking-skeleton_article-store-airflow-webserver_1 exited with code 1
article-store-airflow-scheduler_1  | Fri May 25 15:37:52 UTC 2018 - localhost:5432 still not reachable, giving up
walking-skeleton_article-store-airflow-scheduler_1 exited with code 1
article-store-airflow-worker_1     | Fri May 25 15:37:53 UTC 2018 - localhost:5432 still not reachable, giving up
```
The related postgres container seems alive and well, are these airflow containers misconfigured?
```
walking-skeleton_article-store-postgres_1   docker-entrypoint.sh postgres   Up      5432/tcp
```
They don't have the `DATABASE_URL` variable, or maybe they are talking to a database when they shouldn't.

**Comment by seanwiseman** [comment]
Add Airflow services to project level `docker-compose.yml` was completed [here](https://github.com/libero/walking-skeleton/pull/35).

**Comment by giorgiosironi** [comment]
At the moment `runId` is not in the events, it will probably relate to the Airflow implementation as it has to be passed around.

**Comment by seanwiseman** [comment]
Yes, the addition of the `runId`will come with the changes in the Airflow integration.
