### ISSUE TITLE
Determine RFCs to write

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/walking-skeleton#48]
We need to come up with a list of RFCs that we will want to write. /cc @BlueReZZ

**Comment by thewilkybarkid** [comment]
- High-level architecture (API, event bus and workflows)
- Data model (API and event messages)
- Development process (use of GitHub, versioning, creating specs, libraries and applications etc)

**Comment by BlueReZZ** [comment]
I'd split that as much as possible where they don't directly interrelate - so "high-level architecture" is fine but Data Model Concepts, API Schema and Event Messages Schema might be separate ones - just so we can close them off independently and comments are kept threaded better. Dev Process could perhaps be split too but we should write it as a larger one first and see where it falls apart naturally.

- High-level architecture (API, event bus and workflows)
- Data Model Concepts (examples, use of XML, the way nesting works etc.)
- API Schema (examples and choice of technology/format)
- Event Messages Schema (examples and format)
- Development process

**Comment by thewilkybarkid** [comment]
Let's start with the dev process and high-level architecture, then see what happens with the other 1/3. 

Any thoughts @giorgiosironi, @seanwiseman?

**Comment by BlueReZZ** [comment]
Good idea.

I propose we also put a time limit on them at the outset, so people have an expectation on when they should get involved. We can always extend it if there's a good conversation going or extra work to do.

2 weeks seems okay to me.

**Comment by giorgiosironi** [comment]
Just a perhaps obvious thought: favor larger choices like architecture (what's a distributed system?) to be published first over process (people can adapt).
